GauravKarakoti/Omnifood

- index.html
Added all the images' brief description for the gallery images
> Added all the descriptions for gallery images for website readers

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Closes #20 
Added issue templates and PR template in the repository
> Added issue templates and PR

- css/style.css
- index.html
Title : SCROLL TO TOP BUTTON
Closes #21 
Added a scroll to top button for better UX
Apertre2.0
> added scroll to top button

- css/queries.css
Title : REPLACED EM WITH REM
Closes #4 
REPLACED EM WITH REM
Apertre2.0
> Improved MEDIA QUERIES

- index.html
Title : Dynamic year in footer
Closes #8
added dynamic year in footer
apertre 2.0
> dynamic year in footer

- css/queries.css
- css/style.css
- js/script.js
Title : made the height dynamic and the website responsive
Closes #12 
the diff of height between navbar and hero section made dynamic
apertre 2.0
> dynamic height diff calculator

- License.md
Title :Create License
Closes #<issue no 30>
> License added

- Code of Conduct.md
- Security.md
Title :
Closes #33 >
Please merge my pull request 
@GauravKarakoti
> Create Code of Conduct.md

- css/queries.css
- css/style.css
Title :
Closes #42 >
<--Made the modification to make more attractive to the user -->
<-- Apertre2.0-->
Please merge my pull request
@GauravKarakoti
> Made the modification

- index.html
- js/script.js
Reverts GauravKarakoti/Omnifood#54
> Revert ".."

- README.md
- index.html
- js/script.js
Title : Added js script for trackbutton clicks
Closes #14 
https://github.com/user-attachments/assets/cd3e1105-6289-400d-bb21-9cbff891abb3
> added track button clicks script

- css/queries.css
- css/style.css
- index.html
- js/script.js
Reverts GauravKarakoti/Omnifood#60
> Revert "Responsiveness of website fixed"

- index.html
Title : Lazy Loading for Gallery Images
Closes #7
> lazy-loading gallery images

- css/queries.css
- css/style.css
Title : Gradient Compatibility
Closes #10
Gradient Compatibility set up for older browsers
> Gradient Compatibility

- css/general.css
- css/queries.css
- css/style.css
- index.html
- js/script.js
- manifest.webmanifest
- serviceworker.js
Title : Fixed SEO, Accessibility, and Usability Issues
Closes #63 
1. Made social media links in the footer to open in new tabs.
2. Scroll-to-Top Button: Replaced the Omnifood logo with an arrow icon for clarity.
Moved inline scroll button styles to style.css and add CSS transitions for smooth rotation.
3. Accessibility:
Added aria-label to the CTA form for screen readers.
Ensured all interactive elements (e.g., buttons, links) have focus states defined in CSS.
Audited CSS/JS files to remove unused code.
4. Service Worker:
Ensured the manifest.webmanifest is properly configured and a service worker is registered for PWA functionality.
5. Dependencies:
Loaded the Smoothscroll Polyfill script before script.js to ensure compatibility.
6. The scroll button’s rotation animation felt …
> Fixed SEO, Accessibility, and Usability Issues

- css/queries.css
Title : Fixed: Media Query Breakpoint Ordering Causes Responsive Layout Issues
Closes #49 
1. Converted pixel (px) values to relative units (rem) for improved scalability and accessibility.
2. Updated media query breakpoints to align with modern responsive design standards.
3. Ensured consistent layout behavior across different screen sizes.
@GauravKarakoti Please, review this PR
Apertre 2.0
> Fixed: Media Query Breakpoint Ordering Causes Responsive Layout Issues

- css/general.css
- css/queries.css
- css/style.css
- index.html
- js/script.js
Title : Responsiveness and Compatibility fixed
Closes #36 
This PR add changes that implements Responsiveness and Compatibility fixes.
https://github.com/user-attachments/assets/40f03e6e-e4b3-465f-82cc-bcf69225149d
Apertre 2.0
> Responsiveness Issue Fixed

- css/queries.css
Title : Testimonial Grid Layout Fixed
Closes #52 
Testimonial Grid Layout overflow is fixed in this PR and a single column is implemented with proper sizing of images, texts and user titles.
https://github.com/user-attachments/assets/91a4e4ab-18a3-4a0e-9535-f6b16bb4f279
Apertre 2.0
> Testimonial Section fixed in Mobile Screens

- css/queries.css
Title : Pricing Ribbon fixed and Image in contact form fixed
Closes #6 
This PR fixes the Pricing Ribbon overflow in smaller screens. Also, I have fixed the alignment and visibility of image in contact form for which a reference has also been added in the video.
https://github.com/user-attachments/assets/8a9f170e-6331-4bde-9d3b-8fed63b79eb2
Apertre 2.0
> Best Price Tag fixed and Image in contact form fixed

- css/queries.css
- css/style.css
- js/script.js
- login/app.js
- login/login.html
- login/style.css
Title : Fixed: Responsive Navigation and Sticky Header Adjustments
Closes #50 
1. Fixed responsive navigation and layout flickering issue
2. Fixed forms in login/login.html lack proper client-side validation for email format and password strength.
& Missing error message display for failed form submissions.
Apertre 2.0
> Responsive Navigation and Sticky Header Adjustments

- css/queries.css
- css/style.css
- js/script.js
Closes #13 
https://github.com/user-attachments/assets/59f80166-59d6-41dc-a06d-ded55f6db23d
> mobile navigation click outside close

- css/queries.css
- css/style.css
- js/script.js
Closes #3 
- Added a fallback background color for browsers that do not support backdrop-filter: blur(10px).
- Used background-color: rgba(0, 0, 0, 0.5); as a fallback to ensure readability.
- Applied feature detection using @supports to check for backdrop-filter support.
> Mobile Navigation Overlay Issues

- css/queries.css
- css/style.css
- js/script.js
Closes #11 
https://github.com/user-attachments/assets/44671e83-bdb6-4c60-83bd-fd1571c33211
> Meal Card Height Inconsistency

- css/queries.css
- css/style.css
- index.html
- js/script.js
Title : Fixed Navbar Bug
Closes NA
Fixed Navbar bug.
https://github.com/user-attachments/assets/f7347223-8ae8-456c-ab0f-cb30db540683
Apertre 2.0
> Navbar Fix

- css/style.css
Resolve #103
Closes #103 
Adding hover effects in pricing section 
https://github.com/user-attachments/assets/66d6e6de-69c3-4547-96ea-105ea50d5b26
Aperta 2.0
> Adding hover in pricing section

- .github/dependabot.yml
- .github/workflows/lighthouse.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- lighthouserc.json
Title :
Closes #18 
added the required workflows in addition with lighthouse and the dependabot and due to some reasons could not able to do the cd workflows
> CI workflows

- public/css/style.css
Title : Focus Outline Removal
Closes #2
> Focus Outline Removal

- public/css/style.css
Resolves #109 
Closes #109 
Adding hover effects
Aperta
> Updated with hover effects

- public/index.html
Title : Fix Deprecated Smoothscroll-Polyfill
Closes #120 
This pull request includes changes to the `public/index.html` file to improve code efficiency and remove unnecessary dependencies. The most important changes include removing the smoothscroll polyfill script and simplifying the scroll button visibility logic.
Code efficiency improvements:
* Removed the smoothscroll polyfill script, which is no longer necessary for modern browsers. (`public/index.html`)
* Simplified the scroll button visibility logic by using the `toggle` method with a condition. (`public/index.html`)
Yes, Apertre2.0
> Fix Deprecated Smoothscroll-Polyfill

- public/js/script.js
> Mobile Nav Memory Leak

- public/css/style.css
- public/js/script.js
> Inconsistent Transition Timing

- server.js
> Missing Error Handling in API

- public/css/style.css
- public/js/script.js
- server.js
> Overly Permissive CORS

- public/css/style.css
- public/js/script.js
Title : Disabled scrolling of page when navbar is open
Closes #102 
This PR solves the issue of the website being able to scroll when collapsable navbar is open.
https://github.com/user-attachments/assets/4a2900c7-1340-4b05-98d4-ebf813df06dc
I am sorry, I made changes in my main branch. Please excuse me this time.
Apertre 2.0
> Page scroll disabled when navbar is open

- public/css/style.css
> focus styles

- public/css/general.css
- public/css/queries.css
- public/css/style.css
- public/js/script.js
Title : Fix Unused CSS Classes
Closes #125 
This pull request includes several updates to the CSS and JavaScript files to improve layout handling for browsers that do not support flexbox gap properties. The changes primarily add margin adjustments for various elements when the `.no-flexbox-gap` class is present.
* [`public/css/general.css`](diffhunk://#diff-1c17c009518556f1b8d804ae40539b57ef7b8074636dbcfbc54fae6f3fe78197R238-R241): Added margin adjustments for `.list` and `.list-item` elements when the `.no-flexbox-gap` class is present. 
* [`public/css/queries.css`](diffhunk://#diff-a0717f7faac43d42bcfb280a3c8f2186d0cac11d76fb6e1c2ccb03ad9107f5a1R51-R62): Added margin adjustments for `.hero`, `.main-nav-list`, and `.logos` elements when the `.no-flexbox-gap` class is present. 
* …
> Fix Unused CSS Classes

- public/login/style.css
Title : Fix Login Responsiveness for Mobile 
Closes #138 
Fix the responsiveness for login page
https://github.com/user-attachments/assets/b8b2c232-6989-4555-92c9-830f3b33f6a7
> Fix Login Responsiveness for Mobile 

- public/css/queries.css
Title : Gallery Layout Fix in testimonials section
Closes #80 
This PR fixes the Grid layout for gallery making it a smooth responsive design
https://github.com/user-attachments/assets/c9b756f1-fe54-4f23-b136-753976209a12
Apertre 2.0
> Gallery Layout Fixed for different screens

- public/404.html
- public/css/404.css
- public/js/404.js
> 404 page implementation

- public/css/queries.css
Title : Fixed: Responsive Design - Incomplete Media Queries
Closes #116 
Added media breakpoints in queries.css for 320px and 400px , changed their units as 20rem & 25rem 
Apertre 2.0
> Fixed: Responsive Design - Incomplete Media Queries

- public/css/style.css
> Ios hover state persistence

- public/login/login.html
Title : Replace Twitter icon with Bootstrap Icons in login.html
Closes #147 
This pull request includes updates to the `public/login/login.html` file to enhance the styling of social media icons by switching to Bootstrap Icons.
Styling updates:
* Added a new stylesheet link for Bootstrap Icons to the `public/login/login.html` file.
* Replaced the Font Awesome Twitter icon with the Bootstrap Icons Twitter icon in the "Sign in" section.
* Replaced the Font Awesome Twitter icon with the Bootstrap Icons Twitter icon in the "Sign up" section.
> Replace Twitter icon with Bootstrap Icons in login.html

- public/css/style.css
- public/index.html
> Font loading strategy

- public/index.html
- public/js/script.js
> Content Security Policy

- public/css/style.css
- public/index.html
- public/js/script.js
> centralize animation timing

- server/middlewares/auth.js
Closes #144 
This PR improves the isAuthenticated middleware by adding more robust error handling, better validation, and improved security checks. The changes make the authentication process more reliable and provide clearer feedback when issues occur.
I am in Apertre 2.0.
> Enhance JWT Authentication Middleware with Better Error Handling and Validation

- serviceworker.js
Title : Update service worker cache version and improve fetch strategy
Closes #158 
This pull request includes several updates to the `serviceworker.js` file to improve cache management and enhance the service worker's functionality. The most important changes include versioning the cache, ensuring immediate activation, implementing a network-first strategy with a fallback to cache, and taking control of uncontrolled clients.
Improvements to cache management and service worker functionality:
* [`serviceworker.js`](diffhunk://#diff-12943682e5d32ff6cf0d439857d2f66fa83679ace466571835e44732019f94bcL1-R1): Updated `CACHE_NAME` to `app-cache-v2` for versioning to prevent stale cache.
* [`serviceworker.js`](diffhunk://#diff-12943682e5d32ff6cf0d439857d2f66fa83679ace466571835e44732019f94bcL43-R61): …
> Update service worker cache version and improve fetch strategy

- public/css/style.css
> Fix css bug

- public/css/profile.css
- public/login/style.css
Title : fix: Clean up CSS specificity issues
Closes #154 
This pull request includes several changes to the CSS files to improve the consistency and maintainability of the code. The most important changes include simplifying class selectors and ensuring consistent styling across different components.
Changes to `public/css/profile.css`:
* Simplified the class selector for the avatar by removing the `.profile-info` prefix.
* Simplified the class selector for the email by removing the `.profile-info` prefix.
Changes to `public/login/style.css`:
* Simplified the class selector for the sign-up mode container by removing the `.container` prefix.
> fix: Clean up CSS specificity issues

- public/login/login.html
- public/login/style.css
Title : Enhanced Accessibility Issue in login.html
Closes #184 
Enhanced the accesibility issue in login.html
Added labels for username, password in both signin as well as signup page.
Apertre 2.0
> Improved accessibility in login.html

- public/index.html
https://github.com/user-attachments/assets/254eb397-5c71-4b65-ac07-79bd8f73ac22
Fixed Scrolling
> Refactor scroll button functionality and improve event handling

- README.md
Title : Back to top button in README
Closes #206 
In the `readme.md` added a back to top button.
> Back to top button in README

- public/js/404.js
- public/js/script.js
- public/login/app.js
Title : Add JSDoc comments
Closes #164 
`public/js/404.js`, `public/js/script.js` & `public/login/app.js` added inline documentation to these files.
> Add JSDoc comments

- public/login/login.html
Title : Enhance error messages with ARIA live regions
Closes #157 
Added aria live regions
> Enhance error messages with ARIA live regions

- public/login/app.js
- public/login/style.css
Title : Fix Flawed Password Validation Logic in the Sign-Up Form
Closes #221 
This pull request includes changes to improve the password validation logic and update the styling for the password strength indicator in the login form. The most important changes include updating the validation messages for password requirements and adding a new CSS rule for the password strength indicator.
Improvements to password validation logic:
* [`public/login/app.js`](diffhunk://#diff-e67b2cd082c60ce4c630441455ca96931f82132615301a80b8e7ecdb4961cc5dL189-R198): Updated the password validation logic to provide specific error messages for each password requirement.
Styling updates:
* [`public/login/style.css`](diffhunk://#diff-1c75d783bf0154a55993bdd2aad5d8632e8f9c947719c628c471cf8c6c02f2acR514-R517): Added …
> Fix Flawed Password Validation Logic in the Sign-Up Form

- public/about.html
- public/index.html
Title :
Resolves #239 
Closes #239 
https://github.com/user-attachments/assets/2cf2aac1-c9bb-42a8-9f0b-18691be4f06b
Closes #<issue_no>
> New Web Page Added✅

- public/css/footer.css
- public/css/general.css
- public/css/meals.css
- public/css/pricing.css
- public/index.html
- public/profile.html
Title : reafact Change ion icons to bootstrap icons
Closes #242 
Changed to bootstrap icon
> reafact Change ion icons to bootstrap icons

- public/js/routes/about.js
- public/js/routes/contact.js
- public/js/routes/home.js
- public/js/script.js
> code splitting

- public/css/404.css
- public/css/CTA.css
- public/css/addtional.css
- public/css/feature_how.css
- public/css/fontqueries.css
- public/css/footer.css
- public/css/general.css
- public/css/herosection.css
- public/css/location_navbar.css
- public/css/meals.css
- public/css/navigation.css
- public/css/pricing.css
- public/css/profile.css
- public/css/queries.css
- public/css/scrollbtn.css
- public/css/testimonials.css
Title :
Closes #215 
Changes in CSS Animations
> Changes in CSS Animation

- public/css/404.css
- public/css/CTA.css
- public/css/addtional.css
- public/css/feature_how.css
- public/css/herosection.css
- public/css/location_navbar.css
- public/css/navigation.css
- public/css/pricing.css
- public/css/profile.css
> color contrast improvements

- public/css/404.css
- public/css/CTA.css
- public/css/addtional.css
- public/css/feature_how.css
- public/css/general.css
- public/css/herosection.css
- public/css/location_navbar.css
- public/css/navigation.css
- public/css/pricing.css
- public/css/profile.css
- public/index.html
- public/js/routes/about.js
- public/js/routes/contact.js
- public/js/routes/home.js
- public/js/script.js
> newsletter

- public/css/scrollbtn.css
- public/index.html
> Responsiveness, Accessibility, Duplication, and More

- server/controllers/user.js
Title : Refactor signup verification token generation to use crypto
Closes #228 
This pull request includes changes to the `server/controllers/user.js` file to enhance security and improve code quality. The most important changes include replacing the use of `bcrypt` with `crypto` for generating verification tokens.
Security improvements:
* [`server/controllers/user.js`](diffhunk://#diff-095eda20230f5c8b2bb7a626532d197b53ebbb8e0b40999a03e5bed54c909a84L21-R22): Replaced `bcrypt.hashSync` with `crypto.randomBytes` to generate a more secure verification token.
Code quality improvements:
* [`server/controllers/user.js`](diffhunk://#diff-095eda20230f5c8b2bb7a626532d197b53ebbb8e0b40999a03e5bed54c909a84R7): Added `crypto` module import to support the new token generation method.
> Refactor signup verification token generation to use crypto

- public/about.html
- public/css/feature_how.css
- public/css/general.css
- public/css/herosection.css
- public/css/navigation.css
- public/css/queries.css
- public/css/testimonials.css
- public/index.html
Title :  Improve CSS Responsiveness, Accessibility, and Maintainability
Closes #67 
This PR enhances the existing CSS by implementing responsive design improvements, accessibility compliance fixes, and maintainability best practices. It resolves layout issues, increases accessibility for all users, and optimizes performance while improving code structure.
- This PR was tested on multiple screen sizes to verify responsiveness.
- Used Lighthouse & WCAG tools to ensure accessibility compliance.
- Verified cross-browser compatibility with Chrome, Firefox, and Edge.
Apertre 2.0
> CSS Enhanced for Responsiveness, Accessibility, and Maintainability

- public/js/script.js
Title : Refactor Duplicate and Redundant DOMContentLoaded Handlers
Closes #220 
This pull request refactors the `public/js/script.js` file by modularizing the initialization functions that were previously executed within `DOMContentLoaded` event listeners. This change improves code readability and maintainability.
Refactoring for modularization:
* Converted `DOMContentLoaded` event listeners to individual initialization functions like `initializeSection`, `initializeButtonClick`, `initializeAria`, `initializeLocationInput`, `initializeCTA`, `initializeAuth`, `initializeScrollToTopButton`, `initializeCSPHeader`, and `initializeHeroSection`. 
* Added a new `DOMContentLoaded` event listener at the end of the file to call all the newly created initialization functions.
> Refactor Duplicate and Redundant DOMContentLoaded Handlers

- public/buisness.html
- public/carrier.html
- public/cookingpartner.html
- public/index.html
- public/reciepe.html
Title :
Resolves  #240
Close #240
Closes #<issue_no>
> Cooking Partner and Carrier Page Added

- public/about.html
- public/css/CTA.css
- public/css/general.css
- public/css/herosection.css
- public/css/navigation.css
- public/js/script.js
Title : Fix Root Font Size Override, Button Layout Shifts, Image Scaling, Error Message Dependency, and Mobile Menu UX
Closes #73 
This PR addresses multiple accessibility and UI/UX issues in the project:
- Location: @media (max-width:34rem)
- Issue: html { font-size: 62.5% } may reduce readability on small screens.
- Fix: Adjusted component-specific font sizes instead of modifying root font size.
- Location: .btn:hover { transform: scale(1.05) }
- Issue: Scaling buttons caused unintended content shifts.
- Fix: Applied a method to absorb the scaling effect without layout shifts.
- Location: Hero image max-width (400px/320px in media queries).
- Issue: Images didn't adapt well to ultra-small screens.
- Fix: Used percentage-based widths for better responsiveness.
- Location: .cta-form …
> Responsive Design, Browser Compatibility, and Code Consistency fixed

- public/css/fontqueries.css
- public/css/navigation.css
Title :Fixing Navbar
Closes #234
In navbar section hover effect is overlapped so i want to fix it
https://github.com/user-attachments/assets/3ce26d74-3dbd-4423-b8ac-60678cff1263
Aperta 2.0
> Enhance navigation styles with hover effects for main navigation links

- public/index.html
- public/js/script.js
- public/login/app.js
- server/index.js
Title :CORS policy issue in login
Closes #299 
I have solved the cors issue in login and regestration page
im contrbiuting under apretre 2.0
> solved the cors issue

- public/helpcenter.html
- public/index.html
Title :
Closes #<issue_no>
Resolves #321 
Close #321 
https://github.com/user-attachments/assets/3927443d-256b-4a70-ae57-ac17003f3f45
> Help Center Page Added

- public/css/navigation.css
Title : Added text alignment on Try for free button
Closes #313 
Apertre2.0
> Added text alignment on Try for free button

- public/cookingpartner.html
Title :Add a form for Cooking Partner page linked to netlify forms
Closes #296 
added become partner form and connected it to netlify
im contributing under apretre 2.0
> added become partner form and connected to netlify 

- public/css/general.css
- public/css/navigation.css
Title : Added hover effect on 'works with any diet' section
Closes #314 
Apertre2.0
> Added hover effect on 'works with any diet' section

- public/css/footer.css
- public/css/general.css
- public/css/navigation.css
Title : Improved copyright section 
Closes #315
Apertre2.0
> Improved copyright section 

- public/404.html
- public/about.html
- public/buisness.html
- public/carrier.html
- public/cookingpartner.html
- public/helpcenter.html
- public/reciepe.html
Title :Add favicon to the new pages 
Closes #298 
added favicon to new pages
im contributing under apretre 2.0
> added favicon

- server/index.js
> Refactor server static file handling and improve code formatting

- public/buisness.html
Title : Improve UI for Business Page
Closes #294 
Redesigned the Business page. made it look modern and sleek while maintaining the theme and color scheme of the website.
also it is a fully responsive for mobile too. and made it attractive using animations and transitions 
can you give it a medium tag as it has animations and responsiveness 
Apertre2.0
> Improve UI for Business Page

- public/carrier.html
Title :Improve UI for career page
Closes #297 
Re-created the ui for career page with more attractive colors and ui stylings and also added animations and transitions to make it more visually attractive.
https://github.com/user-attachments/assets/bc2ee8f1-27e2-4f19-bdb0-5696c401b5b1
please add medium tag into it
Apertre2.0
> Improve UI for career page

- public/css/CTA.css
- public/index.html
Title :Fix sign-up btn alignment
Center-aligned the "Sign up" button within its container for better visual alignment.
Closes #348
I am contributing under Apertre2.0
> Fix sign-up btn alignment

- public/helpcenter.html
> Modified the center help page

- public/css/general.css
- public/index.html
> Update   the button

- public/index.html
- public/search.html
- server/controllers/hotelController.js
- server/index.js
- server/models/hotelModel.js
- server/package-lock.json
- server/package.json
- server/routes/hotel.js
Title : Add Backend for Search Functionality
Closes #226 
added backend for search bar where users can get the hotel by city,hotel name and food items
Im contriubting under aprtre 2.0
> Adde backend for search functinlaity

- public/reciepe.html
> Update reciepe section

- package.json
- public/js/script.js
- public/login/app.js
> code improvement

- public/about.html
> Update about section
